blank :- write("|                                                                                               |").

menu:-
write(" _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"),
nl, blank, nl, blank, nl,
write("|                                                                         (^)>                  |"), nl,
write("|                                                                         (/)                   |"), nl,
write("|                                                                         ''                    |"),
nl,
write("|                                           DIEGOD                                              |"),nl,
write("|                                     O caminho da goiaba                                       |"),
nl, blank, nl,
write("|                                    (Digite 1. para jogar)                                     |"),nl,
write("|                                  (Digite 0. para os créditos)                                 |"),nl,
blank, nl, blank, nl, blank, nl,
write("|                                            \\ | /                               ___            |"), nl,
write("|          (^_^)                            - ( ) -                            _| * |_          |"), nl,
write("|           ( )-!                            / | \\                              (-_-)           |"), nl,
write("|          |----|                                                               <( )>           |"), nl,
write("|          @    @                                                                L L            |"), nl,
write("|_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _|"), nl.

creditos:-
write(" _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"),
nl, blank, nl, blank, nl,
write("|                                                                         (^)>                  |"), nl,
write("|                                                                         (/)                   |"), nl,
write("|                                                                         ''                    |"),nl,
write("|                                            DIEGOD                                             |"),nl,
write("|                                      O caminho da goiaba                                      |"),nl, blank,nl,
write("|                                       Diego como Diegod                                       |"),nl,
write("|                                     Anthony (Toms Wenzin)                                     |"),nl,
write("|                                     Bruno (Lancho Wenzin)                                     |"),nl,
write("|                                    Henrique (Wenzin Wenzin)                                   |"),nl,
write("|                                     Thiago (Thigas Wenzin)                                    |"),nl,
write("|                                      Mirlla (MiA Wenzin)                                      |"),nl,
write("|                                     Otávio (Cipris Wenzin)                                    |"),nl,
blank, nl,
write("|                                    (Digite 1. para jogar)                                     |"),nl,
blank, nl, blank, nl, blank, nl,
write("|                                            \\ | /                               ___            |"), nl,
write("|        ヾ(⌐■_■)                           - ( ) -                            _| * |_          |"), nl,
write("|           ( )-!                            / | \\                              (-_-)           |"), nl,
write("|          |----|                                                               <( )>           |"), nl,
write("|          @    @                                                                L L            |"), nl,
write("|_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _|"), nl.